---
# handlers file for ansible-prometheus

- name: reload daemon
  systemd:
    daemon_reload: yes

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted

- name: reload alertmanager
  service:
    name: alertmanager
    state: reloaded

- name: reload systemd and restart alertmanager
  command: systemctl daemon-reload
  notify: restart alertmanager

- name: start grafana service
  service:
   name: grafana-server
   state: started

- name: restart grafana service
  service:
   name: grafana-server
   state: restarted