- name: reload daemon
  systemd:
    daemon_reload: yes

- name: restart alertmanager
  service:
    name: alertmanager
    state: restarted

- name: reload alertmanager
  service:
    name: alertmanager
    state: reloaded

- name: reload systemd and restart alertmanager
  command: systemctl daemon-reload
  notify: restart alertmanager


- name: Reload systemd
  command: systemctl daemon-reload
  listen: systemd_reload