---
- hosts: monitoringserver
  become: yes
  #become_user: root
  become_method: sudo

  tasks:
    - name: Install prometheus
      unarchive:
        src: "https://github.com/prometheus/prometheus/releases/download/v{{ version }}/prometheus-{{ version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Add prometheus user
      user:
        name: prometheus
        system: yes
        createhome: no
        shell: /bin/false


    - name: config file
      template:
       src: prometheus.conf.j2
       dest: /etc/prometheus/prometheus.conf

    - name: Copy systemd init file
      template:
        src: init.service.j2
        dest: /etc/systemd/system/prometheus.service
        notify: systemd_reload

    - name: Start prometheus service
      service:
        name: prometheus
        state: started
        enabled: yes

    - name: Check if prometheus is accessible
      uri:
        url: http://localhost:9090
        method: GET
        status_code: 200
