---
- hosts: hrapp
  become: true
  become_method: sudo
  tasks:

    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes

    - name: install docker
      yum:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
       # - ca-certificates
        - docker


          

    - name: start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add docker user to a super user
      command: usermod -aG docker $USER

    - name: restart docker
      service: 
        name: docker 
        state: restarted

    - name: Run Docker Container
      docker_container:
        name: hrapp_container 
        image: mzmarci/hrapp:v3  
        port: 80:5000
        state: started
        env:
          POSTGRES_HOST: "{{POSTGRES_HOST}}"
          POSTGRES_USER: project
          POSTGRES_DATABASE_NAME: postgres
          POSTGRES_PASSWORD: "{{POSTGRES_PASSWORD}}"
          TO_ADDRESS: mzmazy100@gmail.com
          SOURCE_ADDRESS: mzmazy100@gmail.com
          AWS_REGION_NAME: eu-west-1
          AWS_ACCESS_NAME: "{{AWS_ACCESS_NAME}}"
          AWS_KEY_NAME: "{{AWS_KEY_NAME}}"






