---
- hosts: monitoringserver
  become: yes
  #become_user: root
  become_method: sudo
  tasks:
     - name: Install grafana
       yum:
         name: https://dl.grafana.com/oss/release/grafana-8.1.5.linux-amd64.tar.gz
         state: latest

     - name: Unzip  grafana
       yum:
         name: tar -zxvf grafana-8.1.5.linux-amd64.tar.gz
         state: latest

     - name: "Grafana server started"
       service:
         name: grafana-server
         enabled: true
         state: started

     - name: "Check if Grafana is accessible."
       uri:
         url: http://127.0.0.1:3000
         method: GET
         status_code: 200