---
- hosts: monitoringserver
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - alertmanager

- hosts: hrapp
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter

- hosts: monitoringserver
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus_node_exporter    

- hosts: monitoringserver
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - prometheus

- hosts: monitoringserver
  become: yes
  become_user: root
  become_method: sudo
  roles:
    - grafana