---
- hosts: hrapp
  become: true
  tasks:

    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes

    - name: install dependencies for docker
      yum:
        name: "{{item}}"
        state: lastest
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: yum repo for docker
      yum_repository:
        name: docker
        description: "Repo for Docker"
        file: docker_repo
        baseurl: https://download.docker.com/linux/centos/7/x86_64/stable/
        enabled: yes
        state: lastest
        gpgcheck: no
      
    - name: install docker package
      command: yum install -y docker-ce --nobest
          

    - name: start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add docker user to a super user
      command: usermod -aG docker $USER
      
    - name: restart docker
      service: 
        name: docker 
        state: restarted

