---
- hosts: hrapp
  become: true
  become_method: sudo
  tasks:

    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes

    - name: install docker
      yum:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
       # - ca-certificates
        - docker


          

    - name: start and enable docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Add docker user to a super user
      command: usermod -aG docker $USER

    - name: restart docker
      service: 
        name: docker 
        state: restarted

