---
- hosts: monitoringserver
  become: yes
  #become_user: root
  become_method: sudo
  tasks:
    - name: Download alertmanager
      unarchive:
        src: "https://github.com/prometheus/alertmanager/releases/download/v{{ version }}/alertmanager-{{ version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: no

    - name: Add alertmanager user
      user:
        name: alertmanager
        system: yes
        createhome: no
        shell: /bin/false
    
    - name: Start alertmanager service
      service:
        name: alertmanager
        state: started
        enabled: yes

    - name: Check if alertmanager is accessible
      uri:
        url: http://localhost:9093
        method: GET
        status_code: 200

    - name: enable alertmanager
      command: sudo systemctl restart prometheus-alertmanager


        