---
- hosts: monitoringserver
  become: yes
  #become_user: root
  become_method: sudo

  tasks:
    - name: Add alertmanager user
      user:
        name: alertmanager
        system: yes
        createhome: no
        shell: /bin/false
 
   
    - name: Installing alertmanager, Update and upgrade monitoringserver (monitoring machine)
      yum:
        name: "{{item}}"
        state: latest
        update_cache: yes
      loop:
        - prometheus-alertmanager
        
        
    - name: enable alertmanager
      command: sudo systemctl restart prometheus-alertmanager


        