---
- hosts: monitoringserver
  become: yes
  #become_user: root
  become_method: sudo

  tasks:
  - name: install gpg
  yum:
    name: gnupg,software-properties-common
    state: present
    update_cache: yes

- name: add gpg hey
   yum:
    url: "https://packages.grafana.com/gpg.key"
    validate_certs: no

- name: add repository
  yum_repository:
    repo: "deb https://packages.grafana.com/oss/deb stable main"             
    state: present
    validate_certs: no

- name: install grafana
  yum:
    name: grafana
    state: latest
    update_cache: yes


- name: start service grafana-server
  systemd:
    name: grafana-server
    state: started
    enabled: yes
    
- name: wait for service up
  uri:
    url: "http://127.0.0.1:3000"
    status_code: 200
  register: __result
  until: __result.status == 200
  retries: 120
  delay: 1

