---
- hosts: hrapp
  become: yes
  #become_user: root
  become_method: sudo
  vars:
    version: 1.4.0

  tasks:
 
    - name: Install prometheus node exporter
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Add node_exporter user
      user:
        name: node_exporter
        system: yes
        createhome: no
        shell: /bin/false

    - name: Install Prometheus alert manager systemd service
      template:
        src: nodeexpoterservice.j2
        dest: /etc/systemd/system/nodeexpoterservice

    - name: Start node_exporter service
      service:
        name: node_exporter
        state: started
        enabled: yes

    - name: Check if node exporter emits metrices
      uri:
        url: http://127.0.0.1:9100/metrics
        method: GET
        status_code: 200

        
          
        
    - name: enable node-exporter
      command: sudo systemctl restart prometheus-node-exporter

   
   # - name: Start node-exporter Service
   #   systemd:
   #     name: prometheus-node-exporter
   #     state: started
   #     enabled: yes


 