---
- hosts: monitoringserver
  become: yes
  #become_user: root
  become_method: sudo

  tasks:
   - name: Download grafana
     unarchive:
       src: "https://dl.grafana.com/oss/release/grafana-8.1.5.linux-amd64.tar.gz"
       dest: /tmp/
       remote_src: yes 
        
   - name: unzip the grafana 
     unarchive:
       src: "tar -zxvf grafana-8.1.5.linux-amd64.tar.gz"
       dest: /tmp/
       remote_src: yes

  - name: Add alertmanager user
    user:
      name: alertmanager
      system: yes
      createhome: no
      shell: /bin/false

    - name: install grafana
      yum:
        name: grafana
        state: latest
        update_cache: yes

    - name: start service grafana-server
      systemd:
        name: grafana-server
        state: started
        enabled: yes
        
    - name: wait for service up
      uri:
        url: "http://127.0.0.1:3000"
        status_code: 200
        register: __result
        until: __result.status == 200
        retries: 120
        delay: 1