
    - name: Install node exporter
      unarchive:
        src: "https://github.com/prometheus/node_exporter/releases/download/v{{ version }}/node_exporter-{{ version }}.linux-amd64.tar.gz"
        dest: /tmp/
        remote_src: yes

    - name: Add node_exporter user
      user:
        name: node_exporter
        system: yes
        createhome: no
        shell: /bin/false

    - name: Install nodeexporter service
      template:
        src: init.service.j2
        dest: /etc/systemd/system/nodeexpoterservice


    - name: Check if node exporter emits metrices
      uri:
        url: http://127.0.0.1:9100/metrics
        method: GET
        status_code: -1


   
   # - name: Start node-exporter Service
   #   systemd:
   #     name: prometheus-node-exporter
   #     state: started
   #     enabled: yes


 